sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t bappi2097/docker-react .

script:
  - docker run -e CI=true bappi2097/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-390544275616"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
